spring:
  cloud:
    consul:
      host: ${consul.host}
      port: ${consul.port}
      discovery:
        tags: version=0.0.1,author=cd871127
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s
        instanceId: ${spring.application.name}:${random.value}