version: '3.7'

services:
  consul_1:
    &consul
    container_name: consul_1
    image: 'consul:1.5.2'
    networks:
      cluster-network:
        ipv4_address: 172.28.0.41
    command: ["consul", "agent", "-server", "-data-dir", "/consul/data","-config-dir", "/consul/config","-ui"]
    volumes:
      - ./conf/consul/node_1.json:/consul/config/node_1.json
      - ./conf/consul/config.json:/consul/config/config.json
      - ${DOCKER_VOLUME}/consul/consul_1:/consul/data
  consul_2:
    <<: *consul
    container_name: consul_2
    networks:
      cluster-network:
        ipv4_address: 172.28.0.42
    volumes:
      - ./conf/consul/config.json:/consul/config/config.json
      - ${DOCKER_VOLUME}/consul/consul_2:/consul/data
      - ./conf/consul/node_2.json:/consul/config/node_2.json
  consul_3:
    <<: *consul
    container_name: consul_3
    networks:
      cluster-network:
        ipv4_address: 172.28.0.43
    volumes:
      - ./conf/consul/config.json:/consul/config/config.json
      - ${DOCKER_VOLUME}/consul/consul_3:/consul/data
      - ./conf/consul/node_3.json:/consul/config/node_3.json