#docker-compose版本
version: '3.7'

#创建一个网络
networks:
  dev-network:
    name: dev-network
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

#定义各种服务
services:

#    command: ["redis-server","/data/redis.conf"]
#    volumes:
#      - /home/anthony/dockerVolume/dev/redis:/data