#docker-compose版本
version: '3.7'

#创建一个网络
networks:
  dev-network:
    name: dev-network
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

#定义各种服务
services:
  service-cipher:
    container_name: service-cipher
    image: 'cd871127/service-cipher:0.0.1'
    networks:
      dev-network:
        ipv4_address: 172.28.0.7
    command: ['/bin/sh']
    volumes:
      - /home/anthony/dockerVolume/dev/app/service-cipher/config:/app/config
      - /home/anthony/dockerVolume/dev/app/service-cipher/logs:/app/logs