spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: aaa
          predicates:
            - Path=/xujin
          uri: http://www.baidu.com/
