spring:
  cloud:
    consul:
      host: 172.28.0.3
      port: 8500
      discovery:
        tags: version=0.0.1,author=cd871127
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s
        instanceId: ${spring.application.name}:${random.value}
    gateway:
      #      enabled: true
      #      routes:
      #        - id: service-cipher
      #          uri: lb://SERVICE-CIPHER/
      #          path: /rsa/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true


management:
  endpoint:
    refresh:
      enabled: true
    health:
      show-details: always

server:
  port: 8081