spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    # enabled: true
    # routes:
    #   - id: service-cipher
    #     uri: lb://SERVICE-CIPHER/
    #     path: /rsa/**